In [1]:
print('hello world')

hello world


In [2]:
!nvidia-smi

Sat Jul 26 19:58:14 2025       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 497.29       Driver Version: 497.29       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   41C    P8     4W /  N/A |    605MiB /  4096MiB |     21%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1


Introduction to Tensors

creating tensors

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0750, 0.6714, 0.6094, 0.9241],
        [0.8105, 0.1436, 0.1630, 0.0317],
        [0.3648, 0.9178, 0.2294, 0.7178]])

In [17]:
random_tensor.ndim

2

In [18]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [19]:
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
one_to_ten = torch.arange(start = 1, end = 11, step = 1)

In [24]:
# Creating tensor like zeros
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0] ,
                               dtype = None,
                               device = None,
                               requires_grad = False)
float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_32_tensor.dtype

torch.float32

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype = torch.float16)
float_16_tensor.dtype

torch.float16

In [29]:
some_tensor = torch.rand(3,4)
print(some_tensor)
print(f'shape of tensor: {some_tensor.shape}')
print(f'datatype of tensor: {some_tensor.dtype}')
print(f'device tensor is stored in : {some_tensor.device}')

tensor([[0.5309, 0.6738, 0.5886, 0.8816],
        [0.6411, 0.5421, 0.8823, 0.4312],
        [0.7279, 0.4851, 0.3014, 0.4048]])
shape of tensor: torch.Size([3, 4])
datatype of tensor: torch.float32
device tensor is stored in : cpu


In [30]:
# When you run into issues in PyTorch, it's very often one to do with one of the three attributes above. So when the error messages show up, sing yourself a little song called "what, what, where 

In [31]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [32]:
tensor * 10

tensor([10, 20, 30])

In [33]:
# tensor dont change unless reassigned
tensor

tensor([1, 2, 3])

In [34]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [35]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [36]:
# can also use torch multiplication function for multiplication
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [37]:
# original tensor doesnot changes even if we use multiply function
tensor

tensor([1, 2, 3])

In [38]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [39]:
# broadcasting
tensor_1 = torch.tensor([7])
print(tensor , '*', tensor_1)
print('tensor * tensor_1 =', tensor * tensor_1)


tensor([1, 2, 3]) * tensor([7])
tensor * tensor_1 = tensor([ 7, 14, 21])


In [40]:
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [41]:
# element wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [42]:
# matrix multiplication with matmul function
torch.matmul(tensor, tensor)

tensor(14)

In [43]:
# matrix multipication with @
tensor @ tensor

tensor(14)

In [44]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 1.01 ms


tensor(14)

In [45]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [47]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,8],
                        [9,10],
                        [11,12]])

In [48]:
print(tensor_A)
print(tensor_B)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])


In [49]:
print(tensor_A)
print(tensor_B.T)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[ 7,  9, 11],
        [ 8, 10, 12]])


In [50]:
output = torch.matmul(tensor_A, tensor_B.T)
print(output)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])


In [51]:
# torch.mm is the short form of matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])