In [1]:
print('hello world')

hello world


In [2]:
!nvidia-smi

Mon Jul 28 22:32:51 2025       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 497.29       Driver Version: 497.29       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   45C    P8     5W /  N/A |    576MiB /  4096MiB |     21%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1


Introduction to Tensors

creating tensors

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4534, 0.3076, 0.8715, 0.5051],
        [0.0425, 0.2766, 0.0376, 0.0793],
        [0.7848, 0.8472, 0.7982, 0.1313]])

In [17]:
random_tensor.ndim

2

In [18]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [19]:
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
one_to_ten = torch.arange(start = 1, end = 11, step = 1)

In [24]:
# Creating tensor like zeros
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0] ,
                               dtype = None,
                               device = None,
                               requires_grad = False)
float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_32_tensor.dtype

torch.float32

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype = torch.float16)
float_16_tensor.dtype

torch.float16

In [29]:
some_tensor = torch.rand(3,4)
print(some_tensor)
print(f'shape of tensor: {some_tensor.shape}')
print(f'datatype of tensor: {some_tensor.dtype}')
print(f'device tensor is stored in : {some_tensor.device}')

tensor([[0.4464, 0.6958, 0.3890, 0.2389],
        [0.3450, 0.8755, 0.7159, 0.8970],
        [0.0491, 0.9154, 0.4392, 0.4227]])
shape of tensor: torch.Size([3, 4])
datatype of tensor: torch.float32
device tensor is stored in : cpu


In [30]:
# When you run into issues in PyTorch, it's very often one to do with one of the three attributes above. So when the error messages show up, sing yourself a little song called "what, what, where 

In [31]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [32]:
tensor * 10

tensor([10, 20, 30])

In [33]:
# tensor dont change unless reassigned
tensor

tensor([1, 2, 3])

In [34]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [35]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [36]:
# can also use torch multiplication function for multiplication
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [37]:
# original tensor doesnot changes even if we use multiply function
tensor

tensor([1, 2, 3])

In [38]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [39]:
# broadcasting
tensor_1 = torch.tensor([7])
print(tensor , '*', tensor_1)
print('tensor * tensor_1 =', tensor * tensor_1)


tensor([1, 2, 3]) * tensor([7])
tensor * tensor_1 = tensor([ 7, 14, 21])


In [40]:
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [41]:
# element wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [42]:
# matrix multiplication with matmul function
torch.matmul(tensor, tensor)

tensor(14)

In [43]:
# matrix multipication with @
tensor @ tensor

tensor(14)

In [44]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 1.1 ms


tensor(14)

In [45]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [46]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]], dtype = torch.float32)

tensor_B = torch.tensor([[7,8],
                        [9,10],
                        [11,12]], dtype = torch.float32)

In [47]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])


In [48]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  9., 11.],
        [ 8., 10., 12.]])


In [49]:
output = torch.matmul(tensor_A, tensor_B.T)
print(output)

tensor([[ 23.,  29.,  35.],
        [ 53.,  67.,  81.],
        [ 83., 105., 127.]])


In [50]:
# torch.mm is the short form of matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 23.,  29.,  35.],
        [ 53.,  67.,  81.],
        [ 83., 105., 127.]])

In [51]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features = 2, out_features = 4)
x = tensor_A
output = linear(x)
print(f'input shape: {x.shape}\n')
print(f'output: \n{output}\n\n output shape: {output.shape}')

input shape: torch.Size([3, 2])

output: 
tensor([[2.3378, 0.6147, 0.7451, 0.6186],
        [4.5928, 1.5825, 0.7206, 0.7607],
        [6.8478, 2.5503, 0.6961, 0.9027]], grad_fn=<AddmmBackward0>)

 output shape: torch.Size([3, 4])


In [52]:
tensor_A = torch.tensor([[1,2,7],
                        [3,8,4],
                        [5,6,3]], dtype = torch.float32)

tensor_B = torch.tensor([[7,8],
                        [9,10],
                        [11,12]], dtype = torch.float32)

In [53]:
torch.manual_seed(42)
# creates matrix of dimension in_features * out_features and does matrix multiplication with another matrix
linear = torch.nn.Linear(in_features = 3, out_features = 4)
x = tensor_A
output = linear(x)
print(f'input shape: {x.shape}\n')
print(f'output: \n{output}\n\n output shape: {output.shape}')

input shape: torch.Size([3, 3])

output: 
tensor([[0.8796, 1.1711, 4.2382, 1.2550],
        [5.0434, 1.1233, 4.1835, 3.0947],
        [5.1030, 2.3205, 2.4342, 1.1358]], grad_fn=<AddmmBackward0>)

 output shape: torch.Size([3, 4])


In [54]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [55]:
print(f'minimun: {x.min()}')
print(f'maximum: {x.max()}')
# print(f'mean: {x.mean()}') shows error because it is not in float datatype
print(f"mean: {x.type(torch.float32).mean()}")# x.mean() doesnt work if it isnot in float datatype
print(f'sum: {x.sum()}')

minimun: 0
maximum: 90
mean: 45.0
sum: 450


In [56]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32).mean()), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [57]:
tensor = torch.arange(10, 100, 10)
print(f'tensor: {tensor}')

# argmax and argmin using variable give the index of max and min value respectively where index starts from 0
print(f'index where max value is: {tensor.argmax()}')
# argmax and argmin using torch give the position of max and min value respectively
print(f'position where max value is: {torch.argmax(x)}')
# argmax and argmin using variable give the index of max and min value respectively where index starts from 0
print(f'index where min value is: {tensor.argmin()}')
# argmax and argmin using torch give the position of max and min value respectively
print(f'position where min value is: {torch.argmin(x)}')

tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
index where max value is: 8
position where max value is: 9
index where min value is: 0
position where min value is: 0


In [58]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [59]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [60]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [61]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [62]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [63]:
z = x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [64]:
x.view(1, 7).shape, x.shape

(torch.Size([1, 7]), torch.Size([7]))

In [65]:
# changing the view changes the original tensor as well
z[:, 0] = 9
z, x

(tensor([[9., 2., 3., 4., 5., 6., 7.]]), tensor([9., 2., 3., 4., 5., 6., 7.]))

In [66]:
y = torch.arange(7., 14,)
print(y)
print(x)
x_stacked = torch.stack([x, y], dim = 1)
x_stacked

tensor([ 7.,  8.,  9., 10., 11., 12., 13.])
tensor([9., 2., 3., 4., 5., 6., 7.])


tensor([[ 9.,  7.],
        [ 2.,  8.],
        [ 3.,  9.],
        [ 4., 10.],
        [ 5., 11.],
        [ 6., 12.],
        [ 7., 13.]])

In [67]:
print(f'previous tensor: {x_reshaped}')
print(f'previous tensor shape: {x_reshaped.shape}')

# 
x_squeezed = x_reshaped.squeeze()
print(f'squeezed tensor: {x_squeezed}')
print(f'squeezes tensor shape: {x_squeezed.shape}')

previous tensor: tensor([[9., 2., 3., 4., 5., 6., 7.]])
previous tensor shape: torch.Size([1, 7])
squeezed tensor: tensor([9., 2., 3., 4., 5., 6., 7.])
squeezes tensor shape: torch.Size([7])


In [68]:
tensor = torch.arange(1., 8.)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.])

In [69]:
x_reshaped_col = tensor.reshape(7,1)
# reshaped in row-wise
print(f'reshaped',x_reshaped_col)
# squeezed removes the dimension 1 if there is the dimension of 1
x_squeezed_col_shape = tensor.squeeze()
print(f'squeezed', x_squeezed_col_shape)
print(f'squeezed shape', x_squeezed_col_shape.shape)

# squeezes -> if shape is 1 * n -> n || m * 1 -> m ie remove 1 from the row or column

reshaped tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.]])
squeezed tensor([1., 2., 3., 4., 5., 6., 7.])
squeezed shape torch.Size([7])


In [70]:
print(f'squeezed tensor: {x_squeezed}'+'\n'+f'squeezed tensor shape: {x_squeezed.shape}\n')
# add exta dimension of 1 at row
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f'unsqueezed tensor: {x_unsqueezed}'+'\n'+f'unsqueezed tensor shape: {x_unsqueezed.shape}\n')
# add exta dimension of 1 at row
x_unsqueezed = x_unsqueezed.unsqueeze(dim = 0)
print(f'unsqueezed tensor: {x_unsqueezed}'+'\n'+f'unsqueezed tensor shape: {x_unsqueezed.shape}\n')
# add exta dimension of 1 at column
x_unsqueezed = x_squeezed.unsqueeze(dim = 1)
print(f'unsqueezed tensor: {x_unsqueezed}'+'\n'+f'unsqueezed tensor shape: {x_unsqueezed.shape}\n')
# add exta dimension of 1 at column
x_unsqueezed = x_unsqueezed.unsqueeze(dim = 1)
print(f'unsqueezed tensor: {x_unsqueezed}'+'\n'+f'unsqueezed tensor shape: {x_unsqueezed.shape}\n')


squeezed tensor: tensor([9., 2., 3., 4., 5., 6., 7.])
squeezed tensor shape: torch.Size([7])

unsqueezed tensor: tensor([[9., 2., 3., 4., 5., 6., 7.]])
unsqueezed tensor shape: torch.Size([1, 7])

unsqueezed tensor: tensor([[[9., 2., 3., 4., 5., 6., 7.]]])
unsqueezed tensor shape: torch.Size([1, 1, 7])

unsqueezed tensor: tensor([[9.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.]])
unsqueezed tensor shape: torch.Size([7, 1])

unsqueezed tensor: tensor([[[9.]],

        [[2.]],

        [[3.]],

        [[4.]],

        [[5.]],

        [[6.]],

        [[7.]]])
unsqueezed tensor shape: torch.Size([7, 1, 1])



In [71]:
x_original = torch.rand(size = (244, 244, 3))
x_permuted = x_original.permute(2, 0, 1)

print(f'original tensor shape: {x_original.shape}')
print(f'premuted tensor shape: {x_permuted.shape}')

print(x_permuted)

original tensor shape: torch.Size([244, 244, 3])
premuted tensor shape: torch.Size([3, 244, 244])
tensor([[[0.8854, 0.6274, 0.2969,  ..., 0.9348, 0.6648, 0.2730],
         [0.2243, 0.6615, 0.9576,  ..., 0.6065, 0.0495, 0.7283],
         [0.4460, 0.1840, 0.6964,  ..., 0.3789, 0.5046, 0.4081],
         ...,
         [0.3661, 0.6640, 0.7257,  ..., 0.8274, 0.8848, 0.7138],
         [0.2053, 0.9190, 0.7341,  ..., 0.6263, 0.5069, 0.1175],
         [0.4849, 0.3083, 0.6146,  ..., 0.5859, 0.2638, 0.5896]],

        [[0.5739, 0.2696, 0.8317,  ..., 0.7992, 0.9746, 0.8497],
         [0.8650, 0.2881, 0.1999,  ..., 0.4659, 0.6988, 0.4978],
         [0.7700, 0.3880, 0.8365,  ..., 0.2492, 0.9022, 0.5172],
         ...,
         [0.4588, 0.1238, 0.7433,  ..., 0.5350, 0.3302, 0.1530],
         [0.3377, 0.7629, 0.7967,  ..., 0.7456, 0.4610, 0.2594],
         [0.6021, 0.2703, 0.2679,  ..., 0.1914, 0.4943, 0.8323]],

        [[0.2666, 0.4414, 0.1053,  ..., 0.5783, 0.1774, 0.1579],
         [0.6578, 0.4931,

In [72]:
x = torch.arange(1, 19).reshape(2, 3, 3)
x, x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 torch.Size([2, 3, 3]))

In [73]:
print(f'x: \n{x}')
print(f'first square bracket: \n{x[0]}')
print(f'second square bracket: {x[0][0]}')
print(f'third square bracket: {x[0][0][0]}')

x: 
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])
first square bracket: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
second square bracket: tensor([1, 2, 3])
third square bracket: 1


In [74]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [75]:
x[:, 0]

tensor([[ 1,  2,  3],
        [10, 11, 12]])

In [76]:
x[:, :, 0]

tensor([[ 1,  4,  7],
        [10, 13, 16]])

In [77]:
x[:, 1, 1]

tensor([ 5, 14])

In [78]:
x[1, 0, :]

tensor([10, 11, 12])

In [79]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [80]:
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [81]:
x[:, 0]

tensor([[1, 2, 3]])

In [82]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [83]:
x[:, 1, 1]

tensor([5])

In [84]:
x[0, 0, :]

tensor([1, 2, 3])

In [85]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [86]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [87]:
tensor = torch.from_numpy(array).type(torch.float32)
array = array + 1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]), tensor([2., 3., 4., 5., 6., 7., 8.]))

In [89]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [90]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(f'tensor A: \n{random_tensor_A}\n')
print(f'tensor B: \n{random_tensor_B}\n')
print(f'does tensor A equal tensor B? (anywhere)')
random_tensor_A == random_tensor_B

tensor A: 
tensor([[0.1417, 0.6456, 0.0226, 0.2094],
        [0.6321, 0.0960, 0.4926, 0.1548],
        [0.2549, 0.8068, 0.2459, 0.4506]])

tensor B: 
tensor([[0.5305, 0.5993, 0.4955, 0.1359],
        [0.5243, 0.5060, 0.9585, 0.6795],
        [0.3179, 0.4151, 0.6428, 0.2465]])

does tensor A equal tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
RANDOM_SEED = 42
torch.manual_seed(seed = RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

random_tensor_D = torch.rand(3, 4)
print(f'tensor C:\n{random_tensor_C}')
print(f'tensor D:\n{random_tensor_D}')
print(f'does tensor C equal tensor D? (anywhere)')

random_tensor_C == random_tensor_D

In [96]:
RANDOM_SEED = 42
torch.manual_seed(seed = RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)


# we need to reset the seed everytime 
#when using the .rand function for generating same randomness for different matrix
torch.random.manual_seed(seed = RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
print(f'tensor C:\n{random_tensor_C}')
print(f'tensor D:\n{random_tensor_D}')
print(f'does tensor C equal tensor D? (anywhere)')

random_tensor_C == random_tensor_D

tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
does tensor C equal tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])